spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cruway
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  mustache:
    # テンプレートのエンコード (デフォルト値: UTF-8)
    charset: UTF-8
    # テンプレート名に適用するプレフィックス (デフォルト値: classpath:/templates/)
    prefix: classpath:/templates/
    # テンプレート名に適用するサフィックス (デフォルト値: .mustache)
    suffix: .html

logging:
  level:
    # hibernateSQLをdebugモードに使う
    org.hibernate.SQL: debug
    org.hibernate.type: trace